# Generated by Django 4.2.2 on 2023-06-14 16:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('house', '0002_rename_general_photo_house_general_image'),
        ('gallery', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Flat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_amount', models.IntegerField()),
                ('scheme', models.ImageField(upload_to='flat/scheme/')),
                ('price', models.FloatField()),
                ('square', models.IntegerField()),
                ('kitchen_square', models.IntegerField()),
                ('balcony', models.BooleanField(default=False)),
                ('commission', models.IntegerField()),
                ('district', models.CharField(max_length=200)),
                ('micro_district', models.CharField(max_length=200)),
                ('living_condition', models.CharField(choices=[('draft', 'Чернова'), ('repair', 'Потрібен ремонт'), ('good', 'В жилому стані')], default='draft', max_length=50)),
                ('planning', models.CharField(choices=[('studio-bathroom', 'Студія санвузол'), ('studio', 'Студія')], default='studio', max_length=50)),
                ('corps', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='house.corps')),
                ('floor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='house.floor')),
                ('gallery', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gallery.gallery')),
                ('house', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='house.house')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='house.section')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
