# Generated by Django 4.2.2 on 2023-06-15 19:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('flat', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('confirm', models.BooleanField()),
                ('flat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flat.flat', verbose_name='Кватира')),
            ],
        ),
    ]
