# Generated by Django 4.2.2 on 2023-06-15 19:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Filter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_property', models.CharField(choices=[('living_building', 'Живе приміщення')], default='living_building', max_length=50)),
                ('status_home', models.CharField(choices=[('flats', 'Квартири'), ('cottage', 'Котедж'), ('new-buildings', 'Новобудови'), ('secondary-market', 'Вторинний ринок')], default='flats', max_length=50)),
                ('district', models.CharField(max_length=50)),
                ('micro_district', models.CharField(max_length=50)),
                ('room_count', models.CharField(max_length=50)),
                ('min_price', models.IntegerField(default=1)),
                ('max_price', models.IntegerField(default=99999)),
                ('min_area', models.IntegerField(default=1)),
                ('max_area', models.IntegerField(default=99999)),
                ('purpose', models.CharField(choices=[('many-floors', 'Багатоквартирна'), ('office', 'Офіс'), ('hostel', 'Готель')], default='many_floors', max_length=50)),
                ('purchase_terms', models.CharField(choices=[('mortgage', 'Іпотека'), ('parent-capital', 'Материнський капітал')], default='mortgage', max_length=50)),
                ('condition', models.CharField(choices=[('draft', 'Чернова'), ('repair', 'Потрібен ремонт'), ('good', 'В жилому стані')], default='draft', max_length=50)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Користувач')),
            ],
        ),
    ]
