# Generated by Django 4.2.2 on 2023-06-15 19:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('announcement', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Promotion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_created=True, auto_now=True)),
                ('highlight', models.BooleanField(default=False)),
                ('phrase', models.BooleanField(default=False)),
                ('big_announcement', models.BooleanField(default=False)),
                ('turbo', models.BooleanField(default=False)),
                ('raised', models.BooleanField(default=False)),
                ('price', models.IntegerField(default=250)),
                ('announcement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='announcement.announcement', verbose_name='Заявка')),
            ],
        ),
    ]
