# Generated by Django 4.2.2 on 2023-06-15 19:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('house', '0002_rename_general_photo_house_general_image'),
        ('flat', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChessBoard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('corps', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='house.corps', verbose_name='Корпус')),
                ('flat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flat.flat', verbose_name='Квартира')),
                ('floor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='house.floor', verbose_name='Поверх')),
                ('house', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='house.house', verbose_name='Будинок')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='house.section', verbose_name='Секція')),
            ],
        ),
    ]
