# Generated by Django 4.2.2 on 2023-06-08 19:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Agent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=70)),
                ('surname', models.CharField(max_length=70)),
                ('phone_number', models.IntegerField()),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_role', models.CharField(default='Regular user', max_length=70)),
                ('is_staff', models.BooleanField(default=True)),
                ('is_builder', models.BooleanField(default=False)),
                ('is_notary', models.BooleanField(default=False)),
                ('is_agent', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Sales_departament',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=70)),
                ('surname', models.CharField(max_length=70)),
                ('phone_number', models.IntegerField()),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('me', models.BooleanField()),
                ('me_and_agent', models.BooleanField()),
                ('agent', models.BooleanField()),
                ('disabled', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(max_length=70, unique=True)),
                ('surname', models.CharField(max_length=70)),
                ('phone_number', models.IntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('avatar', models.FileField(upload_to='user/avatar/')),
                ('switch_call_message', models.BooleanField(blank=True, default=False, null=True)),
                ('blacklist', models.BooleanField(blank=True, default=False, null=True)),
                ('agent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='user.agent', verbose_name='Агент')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('role', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='user.role', verbose_name='Роль')),
                ('sales_departament', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='user.sales_departament', verbose_name='Відділ кадрів')),
                ('subscription', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='user.subscription', verbose_name='Підписка')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
