# Generated by Django 4.2.2 on 2023-06-08 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_alter_user_managers_user_is_active_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='role',
            old_name='is_staff',
            new_name='is_regular',
        ),
        migrations.AddField(
            model_name='user',
            name='is_staff',
            field=models.BooleanField(default=True),
        ),
    ]
