# Generated by Django 4.2.2 on 2023-06-11 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_rename_is_staff_role_is_regular_user_is_staff'),
    ]

    operations = [
        migrations.RenameField(
            model_name='role',
            old_name='is_agent',
            new_name='is_admin',
        ),
        migrations.AddField(
            model_name='role',
            name='is_manager',
            field=models.BooleanField(default=False),
        ),
    ]
