# Generated by Django 4.2.2 on 2023-06-10 21:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('gallery', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='House',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('general_photo', models.ImageField(upload_to='house/general_photo/')),
                ('address', models.CharField(max_length=100)),
                ('map_position', models.CharField(max_length=350)),
                ('min_price', models.FloatField()),
                ('price_for_m2', models.IntegerField()),
                ('area', models.FloatField()),
                ('description', models.CharField(max_length=850)),
                ('status_house', models.CharField(choices=[('flats', 'Квартири'), ('cottage', 'Котедж'), ('new-buildings', 'Новобудови'), ('secondary-market', 'Вторинний ринок')], default='flats', max_length=50)),
                ('type_house', models.CharField(choices=[('many-floors', 'Багатоквартирна'), ('office', 'Офіс'), ('hostel', 'Готель')], default='many-floors', max_length=50)),
                ('class_house', models.CharField(choices=[('lux', 'Люкс'), ('elite', 'Елітний'), ('common', 'Стандартний'), ('poor', 'Дешевий')], default='common', max_length=50)),
                ('building_technology', models.CharField(choices=[('frame', 'Монолітний каркас'), ('brick', 'Цегла'), ('foam', 'Піноблок')], default='frame', max_length=50)),
                ('territory', models.CharField(choices=[('close', 'Закрита'), ('open', 'Відкрита'), ('protected', 'Під охороною')], default='close', max_length=50)),
                ('sea_distance', models.IntegerField()),
                ('celling_height', models.CharField(choices=[('2', 'Two'), ('3', 'Three')], default=2, max_length=50)),
                ('gas', models.BooleanField(default=True)),
                ('heating', models.CharField(choices=[('central', 'Центральне'), ('autonomous', 'Автономне')], default='central', max_length=50)),
                ('electricity', models.BooleanField(default=True)),
                ('sewerage', models.CharField(choices=[('central', 'Центральне'), ('autonomous', 'Автономне')], default='central', max_length=50)),
                ('water_supply', models.CharField(choices=[('central', 'Центральне'), ('autonomous', 'Автономне')], default='central', max_length=50)),
                ('arrangement', models.CharField(choices=[('justice', 'Юстиція'), ('finance', 'Фінанси')], default='justice', max_length=50)),
                ('payment', models.CharField(choices=[('mortgage', 'Іпотека'), ('parent-capital', 'Материнський капітал')], default='mortgage', max_length=50)),
                ('contract_sum', models.CharField(choices=[('full', 'Повна'), ('part', 'Частинами')], default='full', max_length=50)),
                ('property_status', models.CharField(choices=[('living_building', 'Живе приміщення')], default='living_building', max_length=50)),
                ('builder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Забудовник')),
                ('gallery', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gallery.gallery', verbose_name='Галерея')),
            ],
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=70)),
                ('house', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='house.house', verbose_name='Будинок')),
            ],
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('text', models.CharField(max_length=450)),
                ('date', models.DateField(auto_now_add=True)),
                ('house', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='house.house', verbose_name='Будинок')),
            ],
        ),
        migrations.CreateModel(
            name='Floor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=70)),
                ('house', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='house.house', verbose_name='Будинок')),
            ],
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=70)),
                ('file', models.FileField(upload_to='house/document/')),
                ('house', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='house.house', verbose_name='Будинок')),
            ],
        ),
        migrations.CreateModel(
            name='Corps',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=70)),
                ('house', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='house.house', verbose_name='Будинок')),
            ],
        ),
    ]
