# Generated by Django 4.2.2 on 2023-06-10 22:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('house', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='house',
            old_name='general_photo',
            new_name='general_image',
        ),
    ]
